name: SAP IDM XML Diff (Single Main Branch)

on:
  workflow_dispatch:
    inputs:
      file_path:
        required: true
        description: 'Path to compare XML file (e.g., testdata/compare.xml)'

jobs:
  xml-visual-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: Prepare XML files
        run: |
          cp ${{ inputs.file_path }} compare.xml
          cp $(dirname ${{ inputs.file_path }})/base.xml base.xml

      - name: Setup Python and dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Split XML and generate HTML diff
        run: |
          source venv/bin/activate
          mkdir -p base_chunks compare_chunks html_output

          # Extract <Package> blocks
          awk '/<Package>/,/<\/Package>/' base.xml > base_packages.xml
          awk '/<Package>/,/<\/Package>/' compare.xml > compare_packages.xml

          # Split into chunks per package
          csplit -f base_chunks/pkg_ -n 4 base_packages.xml '/<Package>/' '{*}' || true
          csplit -f compare_chunks/pkg_ -n 4 compare_packages.xml '/<Package>/' '{*}' || true

          for f in base_chunks/*; do mv "$f" "$f.xml"; done
          for f in compare_chunks/*; do mv "$f" "$f.xml"; done

          # Python script to generate HTML diffs per pair
          python3 <<EOF
          import os, difflib, glob
          
          base_files = sorted(glob.glob('base_chunks/*.xml'))
          compare_files = sorted(glob.glob('compare_chunks/*.xml'))
          os.makedirs('html_output', exist_ok=True)
          
          for i in range(max(len(base_files), len(compare_files))):
              left = open(base_files[i], 'r').readlines() if i < len(base_files) else []
              right = open(compare_files[i], 'r').readlines() if i < len(compare_files) else []
              diff = difflib.HtmlDiff(wrapcolumn=120).make_file(left, right, f"Base pkg_{i}", f"Compare pkg_{i}")
              with open(f"html_output/diff_{i:04}.html", "w") as out:
                  out.write(diff)
          
          with open("html_output/index.html", "w") as index:
              index.write("<html><body><h2>Package Diff Index</h2><ul>")
              for f in sorted(glob.glob("html_output/diff_*.html")):
                  index.write(f"<li><a href='{os.path.basename(f)}'>{os.path.basename(f)}</a></li>")
              index.write("</ul></body></html>")
          EOF

      - name: Upload HTML output
        uses: actions/upload-artifact@v4
        with:
          name: sap-idm-vimdiff-html
          path: html_output/
