name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch to compare from (Base)'
        required: true
        type: choice
        options:
          - main
          - TestWorkflow
      compare_branch:
        description: 'Branch to compare against (Target)'
        required: true
        type: choice
        options:
          - main
          - TestWorkflow
      file_path:
        description: 'Path of file to compare (e.g., src/app/config.yaml)'
        required: true
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
